export const SET_USER_POSITION = 'SET_USER_POSITION';
export const SET_CITY_POSITION = 'SET_CITY_POSITION';
export const FETCH_CURRENT_WEATHER_REQUEST = 'FETCH_CURRENT_WEATHER_REQUEST';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_FAIL = 'FETCH_CURRENT_WEATHER_FAIL';